### ISSUE TITLE
SHA1 use for certificates: vulnerable, deprecated?

### ISSUE THREAD

**Issue by warp9pnt9** [textbrowser/lettera#4]
I've read in many places [1] over the past 2-3 years that SHA1 is deemed vulnerable and should be deprecated for both file checksums (similar to the way MD5 has been deprecated) as well as with certificates (SSL certs).  But I noticed that the certificate generation in Lettera only uses SHA1 hash.  Is this introducing a vulnerability?  Should this be deprecated and changed to SHA256 as a minimum?  Is there any external compatibility limitation that requires SHA1?

[1] https://www.keycdn.com/support/sha1-vs-sha256

**Comment by textbrowser** [comment]
Looking now.

**Comment by textbrowser** [comment]
Are you referring to the SHA-1 digest in Privacy?

**Comment by textbrowser** [comment]
If so, that information is for visual purposes only. That is, the digests represent the fingerprints of the public keys.

**Comment by warp9pnt9** [comment]
Yet, if the visual SHA-1 could be made to appear the same given two inputs, then someone could have changed the certificate without any other way to tell via the interface?  If the visual indicator has no definitive value, it could perhaps be removed from the interface.  If it serves a useful purpose, then it should not be susceptible to manipulation.  I am not sure how I feel about a marginally useful visual indicator that might be unreliable.

**Comment by textbrowser** [comment]
Replaced SHA-1 with SHA-256.

**Comment by textbrowser** [comment]
Closing. Thank you for the help.
