### ISSUE TITLE
Update deprecated JavaMail 1.6.2 to Jakarta Mail 2.0.0.

### ISSUE THREAD

**Issue by warp9pnt9** [textbrowser/lettera#6]
JavaMail (last version 1.6.2) was part of the Java Enterprise Edition, which has been moved to Eclipse Foundation's EE4J project. 
Apparently the name was changed to Jakarta Mail in the process.  The release history of Jakarta Mail starts at 1.6.3, indicating this is a continuation of JavaMail's development.

https://projects.eclipse.org/projects/ee4j.mail/releases/2.0.0

**Comment by textbrowser** [comment]
I missed this ticket. Thank you! Just replaced JavaMail with JakartaMail. Also updated BouncyCastle.

**Comment by textbrowser** [comment]
https://github.com/textbrowser/lettera/commit/2b4efded146048ea795b91289d84ea85aa4c7612

**Comment by warp9pnt9** [comment]
Awesome!  Thanks for that!
